version: "3.8"
services:
  app:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "80:80"
    restart: unless-stopped
  tensorboard:
    container_name: tensorboard
    build:
      context: .
      dockerfile: Dockerfile.board
    ports:
      - "6006:6006"